name: bankend CI
on:
 pull_request:
  types:
    - opened
    - synchronize

jobs:
  ci_job:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'  
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: ｜
          cd demoA/
          mvn  package
